build:
    environment:
        mysql: 5.7

build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: php-scrutinizer-run               
    dependencies:
        before:
          - mysql --version
          - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
    tests:
        override:
            -
                command: './bin/phing unit'
                idle_timeout: 500
                coverage:
                    file: 'test/coverage.xml'
                    format: 'php-clover'
